name: Deploy Images to GHCR

on:
  push:
    branches:
      - main
  workflow_dispatch:

# Set minimal permissions by default
permissions:
  contents: read

jobs:
  push-image:
    runs-on: ubuntu-latest

    # Explicit permissions for this job
    permissions:
      contents: read
      packages: write # Needed to push to GHCR

    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: "Login to GitHub Container Registry"
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: "Set up Docker Buildx"
        uses: docker/setup-buildx-action@v3

      - name: "Build Service Image"
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/ryanleecode/firecrawl-mcp-server:latest
          cache-from: type=registry,ref=ghcr.io/ryanleecode/firecrawl-mcp-server:latest
          cache-to: type=inline
