name: Publish Package

on:
  release:
    types: [created]
  workflow_dispatch:

# Set minimal permissions by default
permissions:
  contents: read

jobs:
  build-and-publish:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            binary-name: firecrawl-mcp-linux-x64
          - os: macos-latest
            binary-name: firecrawl-mcp-darwin-x64
          - os: windows-latest
            binary-name: firecrawl-mcp-windows-x64.exe

    runs-on: ${{ matrix.os }}

    # Explicit permissions for this job - only what's needed for publishing releases
    permissions:
      contents: write # Needed to upload release assets

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build binary
        run: bun run build

      - name: Upload binary to release
        uses: softprops/action-gh-release@v2
        with:
          files: ./dist/firecrawl-mcp${{ matrix.os == 'windows-latest' && '.exe' || '' }}
          name: ${{ matrix.binary-name }}
